### ISSUE TITLE
not able to make it work

### ISSUE THREAD

**Issue by jsen-** [buggerjs/bugger#36]
Hi Jan, 

I'm kind of unable to make it work...
With node 0.10.22 I get an exception.
With node 0.11.8 I get:
```
C:\a\www\x>bugger x.js
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
```
(this is from WS unable to compile the native module, which is optional)

... but when I open chrome-devtools://devtools<b>/bundled/</b>devtools.html?ws=127.0.0.1:8058/websocket in chrome, it seems to be connected ('cause I get a websocket_closed message if I kill the bugger process), but does not show any controls or anything... Just a blank page.

```
C:\a\www\x>bugger x.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```
```
C:\a\www\x>type x.js
for(var i = 0; i< 10; i++) {
        console.log(i);
}
```
```
C:\a\www\x>node -p process.versions
{ http_parser: '1.0',
  node: '0.10.22',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.19',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e' }
```
```
C:\a\www\x>systeminfo
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Original Install Date:     18. 11. 2013, 11:11:28
System Boot Time:          21. 11. 2013, 21:05:54
System Manufacturer:       Hewlett-Packard
System Model:              HP ProBook 6460b
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~1575 Mhz
BIOS Version:              Hewlett-Packard 68SCE Ver. F.08, 26. 8. 2011
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
Total Physical Memory:     4 030 MB
Available Physical Memory: 1 473 MB
Virtual Memory: Max Size:  8 059 MB
Virtual Memory: Available: 5 100 MB
Virtual Memory: In Use:    2 959 MB
Page File Location(s):     C:\pagefile.sys
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) 82579V Gigabit Network Connection
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [02]: Intel(R) Centrino(R) Advanced-N 6205
                                 Connection Name: Wireless Network Connection
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.2.1
                                 IP address(es)
                                 [01]: 192.168.2.123
                                 [02]: fe80::fcec:d563:b1fd:2adc
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
```
```
chrome://version/
Chromium	33.0.1712.0 (Developer Build 235537) 
OS	Windows 
Blink	537.36 (@162160)
JavaScript	V8 3.23.5
Flash	11.7.700.203
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1712.0 Safari/537.36
```

the frontend url mentioned in README.md (<b>chrome-devtools://devtools/devtools.html?ws=127.0.0.1:8058/websocket</b>) seems to just keep loading forever

**Comment by jkrems** [comment]
Assuming this is fixed in 1.0.0, feel free to reopen if the issue still exists.
