### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by omarstreak** [buggerjs/bugger#80]
get the following

```
> bugger@2.3.0 install /usr/local/lib/node_modules/bugger
> node-gyp rebuild

  CXX(target) Release/obj.target/DebugThread/src/module.o
  CXX(target) Release/obj.target/DebugThread/src/thread.o
../src/thread.cc:131:50: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> thread_api = tpl->GetFunction()->NewInstance();
                                                 ^
/Users/oismail/.node-gyp/7.9.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/thread.cc:172:22: error: too many arguments to function call, expected 6, have 7
        argv.size(), argv.data());
                     ^~~~~~~~~~~
/Users/oismail/.node-gyp/7.9.0/include/node/node.h:203:13: note: 'CreateEnvironment' declared here
NODE_EXTERN Environment* CreateEnvironment(IsolateData* isolate_data,
            ^
1 warning and 1 error generated.
make: *** [Release/obj.target/DebugThread/src/thread.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bugger
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bugger@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bugger@2.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bugger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bugger
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bugger
npm ERR! There is likely additional logging output above.
```

I'm running latest node and npm (node 7.9.0, npm 4.5.0)

**Comment by adamkiczula** [comment]
I'm also seeing this on OSX Sierra 10.12.4, node 7.9.0 and npm 4.2.0

**Comment by hybrist** [comment]
I think this is caused by internal changes in node (somewhere around node 6?). I didn't have much time to look into this since I was busy with `--inspect` work. If you're using node 6 or 7, definitely give the native `node --inspect` a try!*

(*) That will give you everything but network request inspection and should work a lot better than bugger does.

**Comment by michahell** [comment]
Confirm also getting this, was trying out `bugger` as alternative to node-inspector and node/v8 debugger itself because of https://github.com/facebook/jest/issues/1652 :(

**Comment by hybrist** [comment]
Hey! Since the current design of bugger is built on top of `node --debug`, I'm not really motivated to make it compile. With node 8 on the horizon that work would have a pretty short lifetime. Another consequence of using `node --debug` in the background is that all the context restrictions that apply to V8's legacy debugger and v8-inspector apply to bugger as well. So, even if it would compile, it would still not stop inside of custom contexts.
